M48
; DRILL file {KiCad 9.0.1} date 2025-05-08T10:03:56+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-08T10:03:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X1.8Y-2.0
X1.9Y-2.0
T2
X1.2Y-2.3
X1.2Y-2.4
M30
